name: LaunchDarkly

on:
  [push]

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        LD_PROJ_KEY: ${{ secrets.LD_PROJECT_KEY }}
        LD_SDK_KEY: ${{ secrets.LD_SDK_KEY }}
    - name: test main
      run: |
        python -m pip install --upgrade pip
        pip install launchdarkly-server-sdk==6.12.1 
        python main.py

